### PR TITLE
CB-11412 Update templates to designate template source dir

### PR DESCRIPTION
**Pull request by carynbear**

### CODE REVIEW

**Comment by devgeeks** [comment]
I'd like to get @hermwong to have a look at this and make sure it has no repercussions for the Desktop App. It's fairly touchy about file locations and doesn't install this template from npm yet.

**Comment by mwbrooks** [comment]
I also left some syntax formatting comments on phonegap/phonegap-template-framework7#6 that are related to this one.

**Comment by carynbear** [comment]
@hermwong could you take a look at this and merge it?

**Comment by devgeeks** [comment]
@hermwong the main thing to check is that it doesn't break the Desktop app.

**Comment by hermwong** [comment]
Is there a reason why the `config.xml` was moved from project's root directory to the `www` directory?

Originally the templates / CLI had the `config.xml` in the `www` directory, but some design changes made to cordova project structure / CLI & templates moved the `config.xml` to the project's root directory.

Are we moving the `config.xml` back to the `www` directory?

**Comment by hermwong** [comment]
The template does load properly when I import the project as an existing project.

screen shot 2016-07-12 at 9 29 37 am

However, we do get some errors (related to the question raised in my previous comment).

screen shot 2016-07-12 at 9 29 52 am

Fortunately, when the `config.xml` move was made in the past, I built in backwards compatibility so that the desktop would [check both locations](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/project-create-open-handlers.js#L216) for the `config.xml`.

**Comment by stevengill** [comment]
@hermwong it looks like for this template, `config.xml` was already in `www` before this PR. @carynbear just kept it in there. I agree though that it should be outside www.

**Comment by carynbear** [comment]
The phonegap cli moves the config.xml file out of the www folder.

**Comment by hermwong** [comment]
This looks good. Feel free to merge the PR and close this issue.

**Pull request merged**
