### PR TITLE
Master

### PR DESCRIPTION
**Pull request by chrisgriffith**
Updated the plugin sources
Updated the icon attribute formatting
Updated the splash screen attribute formatting
Included new icon and splash screen assets
Removed older mobile platforms

### CODE REVIEW

**Comment by mwbrooks** [comment]
Hey @chrisgriffith, this is awesome!

@hollyschinsky and I went over it today. We agree with all of your changes.

A few questions:

1. The whitelist plugin is enabled, so do we want to add a CSP to `index.html`?
2. I think we should move `www/config.xml` to `config.xml`. Thoughts?

I think @hollyschinsky is going to follow up with a few move preferences that we can kill off as well :)

**Comment by hollyschinsky** [comment]
Hey Chris! 

Thanks so much for working on this, it's been a long time coming!!! I had made some notes to do something like this awhile back as well and got distracted, but here are the additional updates I'm thinking we should do:

**Add**
`<preference name="DisallowOverscroll" value="true"/>`

Add WKWebview Engine plugin but commented out maybe? Thoughts on leaving in or commenting out?
`<plugin name="cordova-plugin-wkwebview-engine" source="npm"/>`

Add Statusbar plugin
`<plugin name="cordova-plugin-statusbar" source="npm"/>`

**Change**
`qualifier` to `density` on icons and splash screen definitions

Support Win 10 Splash and Icons, app store icon etc to match latest docs http://cordova.apache.org/docs/en/latest/config_ref/images.html

Remove all of these preferences. They cause too much confusion and many no longer supported or used only for older versions. 

```
    <preference name="permissions"                value="none"/>
    <preference name="orientation"                value="default" />        
    <preference name="target-device"              value="universal" />    
    <preference name="fullscreen"                 value="true" />           
    <preference name="webviewbounce"              value="true" />          
    <preference name="prerendered-icon"           value="true" />           
    <preference name="stay-in-webview"            value="false" />          
    <preference name="ios-statusbarstyle"         value="black-opaque" />  
    <preference name="detect-data-types"          value="true" />          
    <preference name="exit-on-suspend"            value="false" />         
    <preference name="show-splash-screen-spinner" value="true" />           
    <preference name="auto-hide-splash-screen"    value="true" />          
    <preference name="android-installLocation"    value="auto" />     
```

If you feel like making these changes cool, otherwise I can do it after this PR is merged. Just wanted to get your feedback on my suggestions first. 

Thanks!
Holly

**Comment by chrisgriffith** [comment]
A couple of comments.

I thought density was the old attribute and qualifier the new one for
Android.

Let me think on the WKWebview addition. I am leaning toward not including
it.

The rest look fine.

Chris

**Comment by chrisgriffith** [comment]
The Window Icons are a confusing mess:

Cordova List

<platform name="windows">
    <icon src="res/windows/logo.png" width="150" height="150" />
    <icon src="res/windows/smalllogo.png" width="30" height="30" />
    <icon src="res/windows/storelogo.png" width="50" height="50" />
    <icon src="res/Windows/Square44x44Logo.scale-100.png" width="44"
height="44" />
    <icon src="res/Windows/Square44x44Logo.scale-240.png" width="106"
height="106" />
    <icon src="res/Windows/Square70x70Logo.scale-100.png" width="70"
height="70" />
    <icon src="res/Windows/Square71x71Logo.scale-100.png" width="71"
height="71" />
    <icon src="res/Windows/Square71x71Logo.scale-240.png" width="170"
height="170" />
    <icon src="res/Windows/Square150x150Logo.scale-240.png" width="360"
height="360" />
    <icon src="res/Windows/Square310x310Logo.scale-100.png" width="310"
height="310" />
    <icon src="res/Windows/Wide310x150Logo.scale-100.png" width="310"
height="150" />
    <icon src="res/Windows/Wide310x150Logo.scale-240.png" width="744"
height="360" />
</platform>

Build List

<icon platform="winphone" width="44" height="44"
src="res/Square44x44Logo.scale-100.png" />
<icon platform="winphone" width="106" height="106"
src="res/Square44x44Logo.scale-240.png" />
<icon platform="winphone" width="150" height="150"
src="res/Square150x150Logo.scale-100.png" />
<icon platform="winphone" width="360" height="360"
src="res/Square150x150Logo.scale-240.png" />
<icon platform="winphone" width="71" height="71"
src="res/Square71x71Logo.scale-100.png" />
<icon platform="winphone" width="170" height="170"
src="res/Square71x71Logo.scale-240.png" />
<icon platform="winphone" width="310" height="150"
src="res/Wide310x150Logo.scale-100.png" />
<icon platform="winphone" width="744" height="360"
src="res/Wide310x150Logo.scale-240.png" />

My Current
<icon src="www/res/icons/windows/Square71x71Logo.scale-100.png"
 platform="winphone" width="71" height="71" />
<icon src="www/res/icons/windows/Square71x71Logo.scale-240.png"
 platform="winphone" width="170" height="170" />
<icon src="www/res/icons/windows/Square150x150Logo.scale-100.png"
 platform="winphone" width="150" height="150" />
<icon src="www/res/icons/windows/Square150x150Logo.scale-240.png"
 platform="winphone" width="360" height="360" />
<icon src="www/res/icons/windows/Square44x44Logo.scale-100.png"
 platform="winphone" width="44" height="44" />
<icon src="www/res/icons/windows/Square44x44Logo.scale-240.png"
 platform="winphone" width="106" height="106" />
<icon src="www/res/icons/windows/StoreLogo.scale-100.png"
 platform="winphone" width="70" height="70" />
<icon src="www/res/icons/windows/StoreLogo.scale-240.png"
 platform="winphone" width="120" height="120" />
<icon src="www/res/icons/windows/Wide310x150Logo.scale-100.png"
 platform="winphone" width="310" height="150" />
<icon src="www/res/icons/windows/Wide310x150Logo.scale-240.png"
 platform="winphone" width="744" height="360" />
<icon src="www/res/icons/windows/BadgeLogo.scale-100.png"
 platform="winphone" width="24" height="24" />
<icon src="www/res/icons/windows/BadgeLogo.scale-100.png"
 platform="winphone" width="58" height="58" />

Both the Cordova list and the Build List don't align. Then in reading the
Microsoft docs I get more uncertainty.


cg

**Comment by chrisgriffith** [comment]
Adding the CSP would be a good idea. How open should it be? I still
struggle getting that setting right.

Since the is NOT for Build, we should place it outside the www.

Chris

**Comment by chrisgriffith** [comment]
For the moving of the www, should we create a template directory, then
place the config.xml and the www folder in there?

cg

**Comment by mwbrooks** [comment]
> Adding the CSP would be a good idea. How open should it be? I still
struggle getting that setting right.

Almost everyone struggles with getting the settings right. I think we should keep it very open. I compare this to setting up a node.js web server or Linux firewall. It's wildly open at the very start. This just makes early development / setup easier and removes unnecessary barriers-to-entry. After you've created a little web-server or setup your Linux box, you lock-it-down fully, then start to open up what's needed.

I think we should have the same approach with PhoneGap. Wide open CSP (including inline scripts) at the start. This makes it easier to get started. Then documentation explaining how to lock it down. In the longer run, it would be nice to have a linter that catches insecure CSP configurations for release/production builds.

**Comment by mwbrooks** [comment]
> For the moving of the www, should we create a template directory, then
place the config.xml and the www folder in there?

I think we can keep it simple and match the structured used by @hollyschinsky in her Framework 7 template:
https://github.com/phonegap/phonegap-template-framework7

**Comment by chrisgriffith** [comment]
I have been thinking a GUI to write out the CSP sample, but it is way down
on my backlog.

So include this:
<meta http-equiv="Content-Security-Policy" content="default-src 'self'
data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline';
media-src *">

**Comment by devgeeks** [comment]
I agree (reluctantly) with @mwbrooks that the default CSP should be as open as the defaults with the access origin in config.xml. 

But I would LOVE some kind of linting or something to remind folks to lock it down before shipping :/

**Comment by devgeeks** [comment]
Maybe the default could be way open, but have a commented out tighter option (the one @chrisgriffith suggests) above it and maybe a link to http://cspisawesome.com

**Comment by mwbrooks** [comment]
Yea, a linter would be great but is also down the road a little.

I think a link to the great http://cspisawesome.com/ is an excellent start combined with a wide open CSP to get people going without barriers.

**Comment by devgeeks** [comment]
:+1:

**Comment by mwbrooks** [comment]
Hey @chrisgriffith, it looks like we've covered everything except the icon discussion.

Thanks for doing that review! Since we don't plan to support PGB's format, we can toss that to the side. We will want to try to support WP 8.1 and Win 10. I'm afraid that we're going down an icon rabbit hole... the PhoneGap Developer App currently only supports WP 8.1 and [here is our icon set](https://github.com/phonegap/phonegap-app-developer/blob/master/config.xml#L83-L85). Is your set above for Win 10?

**Comment by devgeeks** [comment]
If we are tossing the PGB format, we need the `platform` for the icons to be `wp8` and `windows`, no?

**Comment by devgeeks** [comment]
Another suggestion for the icons/splash config, perhaps they could be wrapped in the appropriate `platform` tag?

```
    <platform name="wp8">
        <icon src="res/wp/ApplicationIcon.png" width="99" height="99" />
        <!-- tile image -->
        <icon src="res/wp/Background.png" width="159" height="159" />
    </platform>
```

Thoughts?

By the way, I am happy to make any of the changes I am suggesting, not just pushing it back on you, @chrisgriffith. I just want this to get merged. :)

**Comment by devgeeks** [comment]
If we leave the CSP wide open, a commented out one like the default suggested above + a link to cspisawesome.com should suffice

```
<meta http-equiv="Content-Security-Policy" content="default-src '*'; style-src 'self' 'unsafe-inline'; media-src *">
```

**Comment by chrisgriffith** [comment]
Was tossing a coin on that change. I fine with that mod. :)

**Comment by chrisgriffith** [comment]
Agreed.

**Comment by devgeeks** [comment]
@chrisgriffith I am going to make some of these changes, then push it to a branch. We have added you to this repo, so we can keep working from a PR from that branch going forward.

PR -- #10

**Comment by chrisgriffith** [comment]
Was making them this evening.

**Comment by devgeeks** [comment]
I have started doing it, I might as well... I have a working windows env now, so...

**Comment by chrisgriffith** [comment]
Ok. I will wrap up my repo and go forward from there.

**Comment by devgeeks** [comment]
:+1:

**Comment by chrisgriffith** [comment]
Pushed my changes to my repo.

**Pull request closed without merging**
