### PR TITLE
Chris Griffith's master

### PR DESCRIPTION
**Pull request by devgeeks**
NOT READY TO BE PULLED IN YET. WORK IN PROGRESS.

Continuation from #9

### CODE REVIEW

**Comment by devgeeks** [comment]
@chrisgriffith

**Comment by devgeeks** [comment]
I think I have also found a wide-open default CSP that works with windows as well as the other platforms.

**Comment by devgeeks** [comment]
I think this is good to review now:

@mwbrooks @chrisgriffith @hollyschinsky etc

**Comment by mwbrooks** [comment]
@devgeeks why are the `wp8` icon and splash commented out?

**Comment by devgeeks** [comment]
They shouldn't be. I think I actually have a tiny bit more to do.

**Comment by devgeeks** [comment]
One last thing (I hope). Since comments are stripped from the `config.xml` when a developer creates an app using the template, I am going to add all the info the comments convey as prose to the README

**Comment by chrisgriffith** [comment]
Sounds like a wise idea.

**Pull request merged**
